# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = 0
b = 1
next_fib = a + b
sum_of_evens = 0

while next_fib < 4_000_000:
    b = a
    a = next_fib
    next_fib = a + b
    if next_fib % 2 == 0:
        sum_of_evens += next_fib

print(f"The sum of all even fibonacci numbers below 4,000,000 is {sum_of_evens}")
